# Analytics

#### Date: 2021/01

#### SUMMARY:

- This notebook represents the project quality analysis of the date exposed right above.

### TEAM:

##### Semester: 2021/01
##### Professor: Hilmer Neri

##### Members:

- Érico Maximiano Bandeira
- Henrique Martins de Messias
- João Vitor Moura Rosa
- Max Henrique Barbosa
- Victor Rodrigues Silva
- Antonio Igor Carvalho
- Gabriel Santos Silva Araújo
- João Paulo Lima da Silva
- Lucas Vieira de Jesus

### LIBRARIES

In [262]:
# Deal with data
import pandas as pd
import numpy as np
import json

# Deal with API request
import urllib3
from urllib3 import request

# Deal with visualization
import seaborn as sns
import matplotlib.pyplot as plt

### GRAPH SETTINGS

In [263]:
%config InlineBackend.figure_format ='retina'
sns.set(font_scale=1.5)
sns.set_style('darkgrid',
              {'xtick.bottom' : True,
               'ytick.left': True,
               'grid.linestyle':'--',
               'font.monospace': ['Computer Modern Typewriter'],
               'axes.edgecolor' : 'white'})

### DATAFRAME SETTINGS

In [264]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

### SonarCloud

#### KEYS

In [265]:
front_key = 'fga-eps-mds_2021-1-PC-GO-Frontend'

In [266]:
profile_key = 'fga-eps-mds_2021.1-Oraculo-Profile'

In [267]:
registros_key = 'fga-eps-mds_2021.1-Oraculo-Processos'

In [268]:
tags_key = 'fga-eps-mds_2021.1-Oraculo-Tags'

#### METRICS

In [269]:
metric_list = ['files',
               'functions',
               'complexity',
               'comment_lines_density',
               'duplicated_lines_density',
               'security_rating',
               'tests',
               'test_success_density',
               'test_execution_time',
               'reliability_rating']

len(metric_list)

10

In [270]:
def generate_metric_string(metric_list):
    metric_str = ''
    
    for metric in metric_list:
        metric_str += metric + ','
        
    return metric_str

In [271]:
metric_str = generate_metric_string(metric_list)

#### URLS

In [272]:
front_url = f"https://sonarcloud.io/api/measures/component_tree?component={front_key}&metricKeys={metric_str}&ps=500"
profile_url = f"https://sonarcloud.io/api/measures/component_tree?component={profile_key}&metricKeys={metric_str}&ps=500"
registros_url = f"https://sonarcloud.io/api/measures/component_tree?component={registros_key}&metricKeys={metric_str}&ps=500"
tags_url = f"https://sonarcloud.io/api/measures/component_tree?component={tags_key}&metricKeys={metric_str}&ps=500"

#### API REQUEST

In [273]:
http = urllib3.PoolManager()

In [274]:
front_request = http.request('GET', front_url)
front_request.status

200

In [275]:
profile_request = http.request('GET', profile_url)
profile_request.status

200

In [276]:
registros_request = http.request('GET', registros_url)
registros_request.status

200

In [277]:
tags_request = http.request('GET', tags_url)
tags_request.status

200

#### JSON DECODING

In [278]:
front_json = json.loads(front_request.data.decode('utf-8'))
profile_json = json.loads(profile_request.data.decode('utf-8'))
registros_json = json.loads(registros_request.data.decode('utf-8'))
tags_json = json.loads(tags_request.data.decode('utf-8'))

## DATA

### PROJECT

In [279]:
project_front_json = front_json['baseComponent']['measures']
project_profile_json = profile_json['baseComponent']['measures']
project_registros_json = registros_json['baseComponent']['measures']
project_tags_json = tags_json['baseComponent']['measures']

In [280]:
project_front_data = pd.DataFrame(project_front_json)
project_profile_data = pd.DataFrame(project_profile_json)
project_registros_data = pd.DataFrame(project_registros_json)
project_tags_data = pd.DataFrame(project_tags_json)

##### FRONT

In [281]:
project_front_data

                     metric value bestValue
0  duplicated_lines_density   2.7     False
1                 functions    82       NaN
2           security_rating   1.0      True
3                     files    58       NaN
4                complexity   100       NaN
5        reliability_rating   1.0      True
6     comment_lines_density   1.4     False

##### BACK

In [282]:
project_profile_data

                     metric value bestValue
0  duplicated_lines_density   0.0      True
1                 functions    25       NaN
2           security_rating   1.0      True
3                     files    12       NaN
4                complexity    44       NaN
5        reliability_rating   1.0      True
6     comment_lines_density   0.8     False

In [283]:
project_registros_data

                     metric value bestValue
0  duplicated_lines_density   0.0      True
1                 functions    26       NaN
2           security_rating   1.0      True
3                     files     9       NaN
4                complexity    42       NaN
5        reliability_rating   1.0      True
6     comment_lines_density   4.1     False

In [284]:
project_tags_data

                     metric value bestValue
0  duplicated_lines_density   0.0      True
1                 functions    11       NaN
2           security_rating   1.0      True
3                     files     7       NaN
4                complexity    13       NaN
5        reliability_rating   1.0      True
6     comment_lines_density   0.0     False

### FILES

In [285]:
def metric_per_file(json):
    file_json = []
    
    for component in json['components']:
        if component['qualifier'] == 'FIL':
            file_json.append(component)
            
    return file_json

In [286]:
front_file_json = metric_per_file(front_json)
profile_file_json = metric_per_file(profile_json)
registros_file_json = metric_per_file(registros_json)
tags_file_json = metric_per_file(tags_json)

In [287]:
def generate_file_dataframe(metric_list, json, language_extension):
    df_columns = metric_list
    df = pd.DataFrame(columns = df_columns)
    
    for file in json:
        try:
            if file['language'] == language_extension:
                for measure in file['measures']:
                    df.at[file['path'], measure['metric']] = measure['value']
        except:
            pass
        
    df.reset_index(inplace = True)
    df = df.rename({'index': 'path'}, axis=1).drop(['files'], axis=1)

    return df

In [288]:
front_files_data = generate_file_dataframe(metric_list, front_file_json, language_extension = 'js')
profile_files_data = generate_file_dataframe(metric_list, profile_file_json, language_extension = 'js')
registros_files_data = generate_file_dataframe(metric_list, registros_file_json, language_extension = 'js')
tags_files_data = generate_file_dataframe(metric_list, tags_file_json, language_extension = 'js')

##### FRONT

In [289]:
front_files_data

,path,functions,complexity,comment_lines_density,duplicated_lines_density,security_rating,tests,test_success_density,test_execution_time,reliability_rating
0,src/App.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
1,src/App.test.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
2,src/Auth/Auth.js,3,3,0.0,0.0,1.0,NaN,100.0,NaN,1.0
3,src/Services/Axios/BaseService/baseService.js,6,13,0.0,0.0,1.0,NaN,100.0,NaN,1.0
4,src/Constants/baseUrls.js,0,0,66.7,0.0,1.0,NaN,100.0,NaN,1.0
5,src/Components/DropDownButton/DivSelectSetor.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
6,src/history.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
7,src/index.js,0,0,20.0,0.0,1.0,NaN,100.0,NaN,1.0
8,src/Pages/CreateProcess/index.js,14,14,0.0,0.0,1.0,NaN,100.0,NaN,1.0
9,src/Pages/LoginScreen/index.js,5,6,0.0,0.0,1.0,NaN,100.0,NaN,1.0
10,src/Pages/AdminScreen/index.js,5,5,0.0,0.0,1.0,NaN,100.0,NaN,1.0
11,src/Pages/ViewProfile/index.js,5,5,0.0,42.0,1.0,NaN,100.0,NaN,1.0
12,src/Pages/ViewProcess/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
13,src/Pages/RegistrationScreen/index.js,8,8,0.0,0.0,1.0,NaN,100.0,NaN,1.0
14,src/Pages/CreateUser/index.js,7,7,0.0,34.0,1.0,NaN,100.0,NaN,1.0
15,src/Components/Header/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
16,src/Components/LoginInput/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
17,src/Components/GenericRedButton/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
18,src/Components/GenericWhiteButton/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
19,src/Components/FilterButton/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
20,src/Components/FieldsGroup/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
21,src/Components/MainButton/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
22,src/Components/SectionMovBlock/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
23,src/Components/SearchBar/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
24,src/Components/GenericBlueButton/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
25,src/Components/DropDownButton/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
26,src/Services/Axios/BaseService/index.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
27,src/Services/Axios/processService.js,0,0,NaN,0.0,1.0,NaN,100.0,NaN,1.0
28,src/Services/Axios/profileService.js,4,10,0.0,0.0,1.0,NaN,100.0,NaN,1.0
29,src/reportWebVitals.js,2,4,0.0,0.0,1.0,NaN,100.0,NaN,1.0
30,src/Routes.js,9,10,0.0,0.0,1.0,NaN,100.0,NaN,1.0
31,src/setupTests.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
32,src/style.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
33,src/Pages/ViewProcess/style.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
34,src/Components/LoginInput/style.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
35,src/Components/MainButton/style.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
36,src/Pages/CreateProcess/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
37,src/Pages/LoginScreen/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
38,src/Pages/AdminScreen/styles.js,0,0,NaN,0.0,1.0,NaN,100.0,NaN,1.0
39,src/Pages/ViewProfile/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
40,src/Pages/RegistrationScreen/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
41,src/Pages/CreateUser/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
42,src/Components/Header/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
43,src/Components/GenericRedButton/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
44,src/Components/GenericWhiteButton/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
45,src/Components/FilterButton/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
46,src/Components/FieldsGroup/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
47,src/Components/SectionMovBlock/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
48,src/Components/SearchBar/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
49,src/Components/GenericBlueButton/styles.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
50,src/Services/Axios/tagsService.js,0,0,NaN,0.0,1.0,NaN,100.0,NaN,1.0

##### BACK

In [290]:
profile_files_data

,path,functions,complexity,comment_lines_density,duplicated_lines_density,security_rating,tests,test_success_density,test_execution_time,reliability_rating
0,src/Database/config/database.js,0,0,6.3,0.0,1.0,NaN,100.0,NaN,1.0
1,src/Model/Department.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
2,src/Utils/hash.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
3,src/index.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
4,src/Database/index.js,6,6,0.0,0.0,1.0,NaN,100.0,NaN,1.0
5,src/Utils/JWT.js,2,4,0.0,0.0,1.0,NaN,100.0,NaN,1.0
6,src/Model/Level.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
7,src/routes.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
8,src/Model/Section.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
9,src/Model/User.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
10,src/Controller/UserController.js,6,23,1.4,0.0,1.0,NaN,100.0,NaN,1.0

In [291]:
registros_files_data

,path,functions,complexity,comment_lines_density,duplicated_lines_density,security_rating,tests,test_success_density,test_execution_time,reliability_rating
0,src/Model/Field.js,1,1,40.0,0.0,1.0,NaN,100.0,NaN,1.0
1,src/index.js,1,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
2,src/Database/index.js,7,13,2.6,0.0,1.0,NaN,100.0,NaN,1.0
3,src/Model/Record.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
4,src/Controller/RecordController.js,11,20,0.7,0.0,1.0,NaN,100.0,NaN,1.0
5,src/routes.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
6,src/Model/Section.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0
7,src/Model/Situation.js,2,2,0.0,0.0,1.0,NaN,100.0,NaN,1.0

In [292]:
tags_files_data

,path,functions,complexity,comment_lines_density,duplicated_lines_density,security_rating,tests,test_success_density,test_execution_time,reliability_rating
0,src/index.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
1,src/Database/index.js,6,6,0.0,0.0,1.0,NaN,100.0,NaN,1.0
2,src/Database/config/index.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
3,src/routes.js,0,0,0.0,0.0,1.0,NaN,100.0,NaN,1.0
4,src/Model/Tag.js,1,1,0.0,0.0,1.0,NaN,100.0,NaN,1.0
5,src/Controller/TagController.js,3,5,0.0,0.0,1.0,NaN,100.0,NaN,1.0

# ANALYSIS

## MAINTAINABILITY

### CODE QUALITY

##### COMPLEXITY

In [293]:
def m1(df):
    
    density_non_complex_files = round((len(df[(df['complexity'].astype(float)/df['functions'].astype(float)) < 10])/len(df))*100, 2)
    
    return density_non_complex_files

##### COMMENTS

In [294]:
def m2(df):
    
    density_comment_files = round((len(df[(df['comment_lines_density'].astype(float) > 10) & (df['comment_lines_density'].astype(float) < 30)])/len(df))*100, 2)
    
    return density_comment_files

##### DUPLICATIONS

In [295]:
def m3(df):
    
    duplication = round((len(df[(df['duplicated_lines_density'].astype(float) < 5)])/len(df))*100, 2)
    
    return duplication

### BLOCKING CODE

#### NON-BLOCKING FILES

In [296]:
def m4(df):
    
    non_blocking_files = round((len(df[(df['security_rating'].astype(float) >= 4)])/len(df))*100,2)
    
    return non_blocking_files

## RELIABILITY

#### TEST SUCCESS

In [297]:
def m5(df):
    
    test_success_file = df[['path', 'test_success_density']]
    test_success_repository = df['test_success_density'].astype(float).mean()
    
    print("Project test unit density: ", test_success_repository)
    
    return test_success_file

#### FAST TESTS

In [298]:
def m6(df):
    
    fast_test_df = df[(df['test_execution_time'].astype(float) < 300)]
    fast_test_df['fast_test'] = fast_test_df['test_execution_time']/fast_test_df['tests']
    
    fast_test_file = fast_test_df[['path', 'fast_test']]
    
    fast_test_repository = fast_test_df['fast_test'].astype(float).mean()
    
    print("Project test unit density: ", fast_test_repository)
    
    return fast_test_file

## PRODUCTIVITY

#### RESOLVED ISSUES' THROUGHPUT

In [299]:
def m7(number_of_issues_resolved, number_of_issues):
    
    resolved_issues_throughput = round((number_of_issues_resolved / number_of_issues) * 100, 2)
    
    return resolved_issues_throughput

#### ISSUE TYPE IN A TIMEFRAME

In [300]:
def density(issue, number_of_issues):
    issue_density = round((issue / number_of_issues) * 100, 2)
    return issue_density

In [301]:
def m8(tag_dict, number_of_issues):
    
    issue_densities = {
        "hotfix": [density(tag_dict["HOTFIX"], number_of_issues)],
        "docs": [density(tag_dict["DOCS"], number_of_issues)],
        "feature": [density(tag_dict["FEATURE"], number_of_issues)],
        "arq": [density(tag_dict["ARQ"], number_of_issues)],
        "devops": [density(tag_dict["DEVOPS"], number_of_issues)],
        "analytics": [density(tag_dict["ANALYTICS"], number_of_issues)],
        "us": [density(tag_dict["US"], number_of_issues)],
        "easy": [density(tag_dict["EASY"], number_of_issues)],
        "medium": [density(tag_dict["MEDIUM"], number_of_issues)],
        "hard": [density(tag_dict["HARD"], number_of_issues)],
        "eps": [density(tag_dict["EPS"], number_of_issues)],
        "mds": [density(tag_dict["MDS"], number_of_issues)]
    }

    issue_densities = pd.DataFrame.from_dict(issue_densities).T.reset_index()
    issue_densities.columns = ['density' ,'percentage']
    
    return issue_densities

#### BUGS RATIO

In [302]:
def m9(tag_dict, number_of_issues): 
    bugs_ratio = round(((tag_dict["DOCS"] + tag_dict["FEATURE"] + tag_dict["ARQ"] + tag_dict["DEVOPS"] + tag_dict["ANALYTICS"]) / number_of_issues) * 100, 2)

    return bugs_ratio

### TIMEFRAME: SPRINT 0

In [303]:
SPRINT = 0
NUMBER_OF_ISSUES_RESOLVED = 43
NUMBER_OF_ISSUES = 54

TAGS = {
    "HOTFIX": 3,
    "DOCS": 16,
    "FEATURE": 6,
    "ARQ": 0,
    "DEVOPS": 20,
    "ANALYTICS": 5,
    "US": 7,
    "EASY": 7,
    "MEDIUM": 5,
    "HARD": 0,
    "EPS": 32,
    "MDS": 1
}

In [304]:
sprint0_m7 = m7(NUMBER_OF_ISSUES_RESOLVED, NUMBER_OF_ISSUES)
sprint0_m8 = m8(TAGS, NUMBER_OF_ISSUES)
sprint0_m9 = m9(TAGS, NUMBER_OF_ISSUES)

### TIMEFRAME: SPRINT 1

In [305]:
SPRINT = 1
NUMBER_OF_ISSUES_RESOLVED = 20
NUMBER_OF_ISSUES = 22

TAGS = {
    "HOTFIX": 0,
    "DOCS": 6,
    "FEATURE": 1,
    "ARQ": 0,
    "DEVOPS": 8,
    "ANALYTICS": 1,
    "US": 3,
    "EASY": 0,
    "MEDIUM": 0,
    "HARD": 0,
    "EPS": 12,
    "MDS": 6
}

In [306]:
sprint1_m7 = m7(NUMBER_OF_ISSUES_RESOLVED, NUMBER_OF_ISSUES)
sprint1_m8 = m8(TAGS, NUMBER_OF_ISSUES)
sprint1_m9 = m9(TAGS, NUMBER_OF_ISSUES)

### TIMEFRAME: SPRINT 2

In [307]:
SPRINT = 2
NUMBER_OF_ISSUES_RESOLVED = 4
NUMBER_OF_ISSUES = 7

TAGS = {
    "HOTFIX": 0,
    "DOCS": 0,
    "FEATURE": 1,
    "ARQ": 0,
    "DEVOPS": 0,
    "ANALYTICS": 0,
    "US": 3,
    "EASY": 0,
    "MEDIUM": 2,
    "HARD": 0,
    "EPS": 0,
    "MDS": 6
}

In [308]:
sprint2_m7 = m7(NUMBER_OF_ISSUES_RESOLVED, NUMBER_OF_ISSUES)
sprint2_m8 = m8(TAGS, NUMBER_OF_ISSUES)
sprint2_m9 = m9(TAGS, NUMBER_OF_ISSUES)

### TIMEFRAME: SPRINT 3

In [309]:
SPRINT = 3
NUMBER_OF_ISSUES_RESOLVED = 3
NUMBER_OF_ISSUES = 8

TAGS = {
    "HOTFIX": 0,
    "DOCS": 1,
    "FEATURE": 4,
    "ARQ": 0,
    "DEVOPS": 0,
    "ANALYTICS": 0,
    "US": 0,
    "EASY": 3,
    "MEDIUM": 1,
    "HARD": 2,
    "EPS": 2,
    "MDS": 5
}

In [310]:
sprint3_m7 = m7(NUMBER_OF_ISSUES_RESOLVED, NUMBER_OF_ISSUES)
sprint3_m8 = m8(TAGS, NUMBER_OF_ISSUES)
sprint3_m9 = m9(TAGS, NUMBER_OF_ISSUES)

### TIMEFRAME: SPRINT 4

In [311]:
SPRINT = 4
NUMBER_OF_ISSUES_RESOLVED = 7
NUMBER_OF_ISSUES = 7

TAGS = {
    "HOTFIX": 0,
    "DOCS": 0,
    "FEATURE": 2,
    "ARQ": 0,
    "DEVOPS": 3,
    "ANALYTICS": 1,
    "US": 0,
    "EASY": 1,
    "MEDIUM": 2,
    "HARD": 1,
    "EPS": 1,
    "MDS": 5
}

In [312]:
sprint4_m7 = m7(NUMBER_OF_ISSUES_RESOLVED, NUMBER_OF_ISSUES)
sprint4_m8 = m8(TAGS, NUMBER_OF_ISSUES)
sprint4_m9 = m9(TAGS, NUMBER_OF_ISSUES)

### TIMEFRAME: SPRINT 4

In [313]:
SPRINT = 5
NUMBER_OF_ISSUES_RESOLVED = 15
NUMBER_OF_ISSUES = 16

TAGS = {
    "HOTFIX": 0,
    "DOCS": 0,
    "FEATURE": 4,
    "ARQ": 0,
    "DEVOPS": 1,
    "ANALYTICS": 0,
    "US": 2,
    "EASY": 3,
    "MEDIUM": 1,
    "HARD": 0,
    "EPS": 1,
    "MDS": 8
}

In [314]:
sprint5_m7 = m7(NUMBER_OF_ISSUES_RESOLVED, NUMBER_OF_ISSUES)
sprint5_m8 = m8(TAGS, NUMBER_OF_ISSUES)
sprint5_m9 = m9(TAGS, NUMBER_OF_ISSUES)

### METRIC RESULTS

#### M1 Results

In [315]:
front_m1 = m1(front_files_data)
profile_m1 = m1(profile_files_data)
registros_m1 = m1(registros_files_data)
tags_m1 = m1(tags_files_data)

m1_results = {"Repository": ["Front End", "Profile", "Registros", "Tags"], "Results": [front_m1, profile_m1, registros_m1, tags_m1]}

m1_results = pd.DataFrame(data=m1_results)

m1_results.style.hide_index

m1_results

  Repository  Results
0  Front End    49.02
1    Profile    81.82
2  Registros    87.50
3       Tags    66.67

#### M2 Results

In [316]:
front_m2 = m2(front_files_data)
profile_m2 = m2(profile_files_data)
registros_m2 = m2(registros_files_data)
tags_m2 = m2(tags_files_data)

m2_results = {"Repository": ["Front End", "Profile", "Registros", "Tags"], "Results": [front_m2, profile_m2, registros_m2, tags_m2]}

m2_results = pd.DataFrame(data=m2_results)

m2_results.style.hide_index

m2_results

  Repository  Results
0  Front End     1.96
1    Profile     0.00
2  Registros     0.00
3       Tags     0.00

#### M3 Results

In [317]:
front_m3 = m3(front_files_data)
profile_m3 = m3(profile_files_data)
registros_m3 = m3(registros_files_data)
tags_m3 = m3(tags_files_data)

m3_results = {"Repository": ["Front End", "Profile", "Registros", "Tags"], "Results": [front_m3, profile_m3, registros_m3, tags_m3]}

m3_results = pd.DataFrame(data=m3_results)

m3_results.style.hide_index

m3_results

  Repository  Results
0  Front End    96.08
1    Profile   100.00
2  Registros   100.00
3       Tags   100.00

#### M4 Results

In [318]:
front_m4 = m4(front_files_data)
profile_m4 = m4(profile_files_data)
registros_m4 = m4(registros_files_data)
tags_m4 = m4(tags_files_data)

m4_results = {"Repository": ["Front End", "Profile", "Registros", "Tags"], "Results": [front_m4, profile_m4, registros_m4, tags_m4]}

m4_results = pd.DataFrame(data=m4_results)

m4_results.style.hide_index

m4_results

  Repository  Results
0  Front End      0.0
1    Profile      0.0
2  Registros      0.0
3       Tags      0.0

#### M5 Results

In [319]:
front_m5 = m5(front_files_data)
profile_m5 = m5(profile_files_data)
registros_m5 = m5(registros_files_data)
tags_m5 = m5(tags_files_data)

m5_results = {"Repository": ["Front End", "Profile", "Registros", "Tags"], "Results": [front_m5, profile_m5, registros_m5, tags_m5]}

m5_results = pd.DataFrame(data=m5_results)

m5_results.style.hide_index

m5_results

Project test unit density:  100.0
Project test unit density:  100.0
Project test unit density:  100.0
Project test unit density:  100.0

  Repository                                            Results
0  Front End                                                ...
1    Profile                                  path test_succ...
2  Registros                                   path test_suc...
3       Tags                                path test_succes...

#### M6 Results

In [320]:
front_m6 = m6(front_files_data)
profile_m6 = m6(profile_files_data)
registros_m6 = m6(registros_files_data)
tags_m6 = m6(tags_files_data)

m6_results = {"Repository": ["Front End", "Profile", "Registros", "Tags"], "Results": [front_m6, profile_m6, registros_m6, tags_m6]}

m6_results = pd.DataFrame(data=m6_results)

m6_results.style.hide_index

m6_results

Project test unit density:  nan
Project test unit density:  nan
Project test unit density:  nan
Project test unit density:  nan

  Repository                                            Results
0  Front End  Empty DataFrame
Columns: [path, fast_test]
Ind...
1    Profile  Empty DataFrame
Columns: [path, fast_test]
Ind...
2  Registros  Empty DataFrame
Columns: [path, fast_test]
Ind...
3       Tags  Empty DataFrame
Columns: [path, fast_test]
Ind...

#### M7 Results

In [321]:
sprint0_m7
sprint1_m7
sprint2_m7
sprint3_m7
sprint4_m7
sprint5_m7

m7_results = {"Sprint": [0,1,2,3,4,5], "Results": [sprint0_m7,sprint1_m7,sprint2_m7,sprint3_m7,sprint4_m7,sprint5_m7]}
m7_results = pd.DataFrame(data=m7_results)
m7_results

   Sprint  Results
0       0    79.63
1       1    90.91
2       2    57.14
3       3    37.50
4       4   100.00
5       5    93.75

#### M8 Results

In [331]:
sprint0_m8
sprint1_m8
sprint2_m8
sprint3_m8
sprint4_m8
sprint5_m8

m8_list = [sprint0_m8,sprint1_m8,sprint2_m8,sprint3_m8,sprint4_m8,sprint5_m8]

for i in range(len(m8_list)):
    print("Sprint {sprint}".format(sprint=i))
    display(m8_list[i])

Sprint 0

      density  percentage
0      hotfix        5.56
1        docs       29.63
2     feature       11.11
3         arq        0.00
4      devops       37.04
5   analytics        9.26
6          us       12.96
7        easy       12.96
8      medium        9.26
9        hard        0.00
10        eps       59.26
11        mds        1.85

Sprint 1

      density  percentage
0      hotfix        0.00
1        docs       27.27
2     feature        4.55
3         arq        0.00
4      devops       36.36
5   analytics        4.55
6          us       13.64
7        easy        0.00
8      medium        0.00
9        hard        0.00
10        eps       54.55
11        mds       27.27

Sprint 2

      density  percentage
0      hotfix        0.00
1        docs        0.00
2     feature       14.29
3         arq        0.00
4      devops        0.00
5   analytics        0.00
6          us       42.86
7        easy        0.00
8      medium       28.57
9        hard        0.00
10        eps        0.00
11        mds       85.71

Sprint 3

      density  percentage
0      hotfix         0.0
1        docs        12.5
2     feature        50.0
3         arq         0.0
4      devops         0.0
5   analytics         0.0
6          us         0.0
7        easy        37.5
8      medium        12.5
9        hard        25.0
10        eps        25.0
11        mds        62.5

Sprint 4

      density  percentage
0      hotfix        0.00
1        docs        0.00
2     feature       28.57
3         arq        0.00
4      devops       42.86
5   analytics       14.29
6          us        0.00
7        easy       14.29
8      medium       28.57
9        hard       14.29
10        eps       14.29
11        mds       71.43

Sprint 5

      density  percentage
0      hotfix        0.00
1        docs        0.00
2     feature       25.00
3         arq        0.00
4      devops        6.25
5   analytics        0.00
6          us       12.50
7        easy       18.75
8      medium        6.25
9        hard        0.00
10        eps        6.25
11        mds       50.00

#### M9 Results

In [337]:
sprint0_m9
sprint1_m9
sprint2_m9
sprint3_m9
sprint4_m9
sprint5_m9

m9_results = {"Sprint": [0,1,2,3,4,5], "Results": [sprint0_m9,sprint1_m9,sprint2_m9,sprint3_m9,sprint4_m9,sprint5_m9]}
m9_results = pd.DataFrame(data=m9_results)
m9_results

   Sprint  Results
0       0    87.04
1       1    72.73
2       2    14.29
3       3    62.50
4       4    85.71
5       5    31.25